services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgrespassword
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}
  web:
    image: ${WEB_IMAGE:-ghcr.io/marka2g/belly_bot:latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      PHX_HOST: "localhost"
    secrets:
      - databaseurl
      - secretkeybase
    ports:
      - 4000:4000
    command: >
      bash -c "bin/migrate && \
              bin/server" 
    depends_on:
      - db

volumes:
  db_data:

secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
    # file: ./secrets/${ENVIRONMENT}/.postgrespassword
  secretkeybase:
    file: ./secrets/.secretkeybase
    # file: ./secrets/${ENVIRONMENT}/.secretkeybase
  databaseurl:
    file: ./secrets/.databaseurl
    # file: ./secrets/${ENVIRONMENT}/.databaseurl