# in ci_cd.yaml

name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Compile with mix test, format, dialyzer & unused deps check
    env:
      MIX_ENV: test
    steps:
      - name: Check unused dependencies 
        run: mix deps.unlock --check-unused

      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions 
          version-type: strict

      - name: Cache Deps Directory
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Get Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix compile --warnings-as-errors

      - name: Run Tests
        run: mix test --max-failures 1 --trace --warnings-as-errors

      - name: Check Formatting 
        run: mix format --check-formatted

      - name: Run Dialyzer for Static Analysis 
        run: mix dialyzer --format github